too few successful tests, not using stored timings
Running doctests with ID 2015-08-31-16-32-33-17491188.
Git branch: master
Using --optional=gcc,mpir,python2,sage,scons
Doctesting 1 file.
sage -t smt_z3py.py
**********************************************************************
File "smt_z3py.py", line 184, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-6==0],x*x-36==0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[1]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(6)==Integer(0)],x*x-Integer(36)==Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 186, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-6==0,x+6==0],x*x-36==0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[2]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(6)==Integer(0),x+Integer(6)==Integer(0)],x*x-Integer(36)==Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 188, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x*x-36==0],x-6==0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[3]>", line 1, in <module>
        SMT_Z3.imply([x*x-Integer(36)==Integer(0)],x-Integer(6)==Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 190, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-6==0],x-36==0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[4]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(6)==Integer(0)],x-Integer(36)==Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 192, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply(x-7>=0,x>=6)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[5]>", line 1, in <module>
        SMT_Z3.imply(x-Integer(7)>=Integer(0),x>=Integer(6))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 194, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply(x-7>=0,x>=8)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[6]>", line 1, in <module>
        SMT_Z3.imply(x-Integer(7)>=Integer(0),x>=Integer(8))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 196, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply(x-6>=0,x-7>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[7]>", line 1, in <module>
        SMT_Z3.imply(x-Integer(6)>=Integer(0),x-Integer(7)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 198, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-7>=0,y+5>=0],x+y-3>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[8]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],x+y-Integer(3)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 200, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-7>=0,y+5>=0],x+y-2>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[9]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],x+y-Integer(2)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 202, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-2*y>=0,y-1>=0],x-2>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[10]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(2)*y>=Integer(0),y-Integer(1)>=Integer(0)],x-Integer(2)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function mul_vararg at 0x7f6b952946e0>
**********************************************************************
File "smt_z3py.py", line 206, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-7>=0,y+5>=0],x+y-2>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[12]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],x+y-Integer(2)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 208, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x^2-9>=0,x>=0],x-3>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[13]>", line 1, in <module>
        SMT_Z3.imply([x**Integer(2)-Integer(9)>=Integer(0),x>=Integer(0)],x-Integer(3)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 210, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([1/2*x**2 - 3/28*x + 1 >= 0],1/20*x**2 - 9/20*x + 1 >= 0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[14]>", line 1, in <module>
        SMT_Z3.imply([Integer(1)/Integer(2)*x**Integer(2) - Integer(3)/Integer(28)*x + Integer(1) >= Integer(0)],Integer(1)/Integer(20)*x**Integer(2) - Integer(9)/Integer(20)*x + Integer(1) >= Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function mul_vararg at 0x7f6b952946e0>
**********************************************************************
File "smt_z3py.py", line 212, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([1/20*x**2 - 9/20*x + 1 >= 0],1/2*x**2 - 3/28*x + 1 >= 0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[15]>", line 1, in <module>
        SMT_Z3.imply([Integer(1)/Integer(20)*x**Integer(2) - Integer(9)/Integer(20)*x + Integer(1) >= Integer(0)],Integer(1)/Integer(2)*x**Integer(2) - Integer(3)/Integer(28)*x + Integer(1) >= Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function mul_vararg at 0x7f6b952946e0>
**********************************************************************
File "smt_z3py.py", line 214, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-6==0],x*x-36==0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[16]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(6)==Integer(0)],x*x-Integer(36)==Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 216, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x+7>=0,y+5>=0],x*y+36>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[17]>", line 1, in <module>
        SMT_Z3.imply([x+Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],x*y+Integer(36)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 218, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x+7>=0,y+5>=0],x*y+35>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[18]>", line 1, in <module>
        SMT_Z3.imply([x+Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],x*y+Integer(35)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 220, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x+7>=0,y+5>=0],x*y-35>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[19]>", line 1, in <module>
        SMT_Z3.imply([x+Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],x*y-Integer(35)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 222, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x+7>=0],x-8>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[20]>", line 1, in <module>
        SMT_Z3.imply([x+Integer(7)>=Integer(0)],x-Integer(8)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 224, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x+7>=0],x+8>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[21]>", line 1, in <module>
        SMT_Z3.imply([x+Integer(7)>=Integer(0)],x+Integer(8)>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 226, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x+7>=0],x+8.9>=0)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[22]>", line 1, in <module>
        SMT_Z3.imply([x+Integer(7)>=Integer(0)],x+RealNumber('8.9')>=Integer(0))
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
File "smt_z3py.py", line 228, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x>=7,y>=5],x*y>=35)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[23]>", line 1, in <module>
        SMT_Z3.imply([x>=Integer(7),y>=Integer(5)],x*y>=Integer(35))
      File "./smt_z3py.py", line 247, in imply
        gs = [SMT_Z3.to_z3exp(g, is_real=True) for g in gs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function mul_vararg at 0x7f6b952946e0>
**********************************************************************
File "smt_z3py.py", line 230, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x>=-7,y>=-5],x*y>=35)
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[24]>", line 1, in <module>
        SMT_Z3.imply([x>=-Integer(7),y>=-Integer(5)],x*y>=Integer(35))
      File "./smt_z3py.py", line 247, in imply
        gs = [SMT_Z3.to_z3exp(g, is_real=True) for g in gs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function mul_vararg at 0x7f6b952946e0>
**********************************************************************
File "smt_z3py.py", line 232, in smt_z3py.SMT_Z3.imply
Failed example:
    SMT_Z3.imply([x-7>=0,y+5>=0],[x+y-2>=0,x>=2-y])
Exception raised:
    Traceback (most recent call last):
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/tnguyen/Src/Devel/SAGE/sage-6.8-x86_64-Linux/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest smt_z3py.SMT_Z3.imply[25]>", line 1, in <module>
        SMT_Z3.imply([x-Integer(7)>=Integer(0),y+Integer(5)>=Integer(0)],[x+y-Integer(2)>=Integer(0),x>=Integer(2)-y])
      File "./smt_z3py.py", line 246, in imply
        fs = [SMT_Z3.to_z3exp(f, is_real=True) for f in fs]
      File "./smt_z3py.py", line 169, in to_z3exp
        oprs = [SMT_Z3.to_z3exp(o, is_real) for o in oprs]
      File "./smt_z3py.py", line 170, in to_z3exp
        z3exp = SMT_Z3._reduce(p.operator(),oprs)
      File "./smt_z3py.py", line 124, in _reduce
        raise AssertionError('unknown op: {}'.format(op))
    AssertionError: unknown op: <function add_vararg at 0x7f6b95294668>
**********************************************************************
1 item had failures:
  24 of  27 in smt_z3py.SMT_Z3.imply
    [57 tests, 24 failures, 0.10 s]
----------------------------------------------------------------------
sage -t smt_z3py.py  # 24 doctests failed
----------------------------------------------------------------------
Total time for all tests: 0.3 seconds
    cpu time: 0.1 seconds
    cumulative wall time: 0.1 seconds
